<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H21MM63" name="Test" tests="1" failures="1" timestamp="16 Dec 2020 17:15:53 GMT" time="0.049" errors="0">
  <testcase name="check" time="0.012" classname="selenium.com.test.Selenium_Gurushools_maven.Validation2">
    <failure type="java.lang.AssertionError" message="number not equal expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: number not equal expected [0] but found [1]
	at selenium.com.test.Selenium_Gurushools_maven.Validation2.check(Validation2.java:11)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- check -->
</testsuite> <!-- Test -->
